### ISSUE TITLE
Fix gallery

### ISSUE THREAD

**Issue by TISparta** [CP-UTEC/Lessons#2]
The view in both cellphones and laptops is not the best. The pictures are not well scaled in phones. The background of the carousel should change. It must be responsive

**Comment by GioCS17** [comment]
Estuve intentando con padding, vertical-align y otras cosas y nada. Me parece que la solucion va por crear estilos para imagenes con distintos tamaños o tal vez hay un trabajo previo sobre las imagenes para que tengan un mismo tamaño todas. Voy a investigar mas de esto.

**Comment by GioCS17** [comment]
Creo que hay una mejor forma para ver las fotos. No toquen esta parte. Lo ire trabajando.
