### ISSUE TITLE
Improve content of class 07

### ISSUE THREAD

**Issue by TISparta** [CP-UTEC/Lessons#5]
- Binary representation section. 
* In C++, Java and Python, the int and long long uses 32-bits and 64-bits ? Pyhton ?

-  Bitwise operations 
* Make and overview of the operator and its table of truth
* The codes can be inline for simplicity. Morever # is not for comments in c++. Fix the codes

**Comment by GioCS17** [comment]
@TISparta  Bitwise operations ya estaba puesto en la clase o a que mas te refieres?

**Comment by TISparta** [comment]
Me refiero a que arregles esa sección en general (contenido más didáctico, códigos que funcionen y que no combinen sintaxis de Python y c++, dar ejemplos de situaciones en las que es útil, etc)
